version: 1.0.{build}
image: Visual Studio 2019

configuration:
  - Debug
  - Release

platform:
  - Win32
  - x64

environment:
  PATH: $(PATH);C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\msys64\opt\bin
  MPCHC_WINSDK_VER: 10
  MPCHC_MSYS: C:\MSYS64
  MPCHC_MINGW32: C:\MSYS64\mingw32
  MPCHC_MINGW64: C:\MSYS64\mingw64
  MSYSTEM: MINGW32
  MSYS2_PATH_TYPE: inherit
  MPCHC_GIT: C:\Program Files\Git
  MPCHC_PYTHON: C:\Python38-x64

clone_script:
  - git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - update_version.bat # must go before git checkout to pick up the branch name
  - git checkout -qf %APPVEYOR_REPO_COMMIT%

install:
  - pacman -S --noconfirm --needed nasm yasm

build_script:
  - for /f %%v IN ('git describe') do set VERSION=%%v
  - nuget restore -PackagesDirectory packages src\mpc-hc\packages.config
  - set BITNESS=%PLATFORM:~-2%
  - wget -nv "https://exiftool.org/exiftool-13.30_%BITNESS%.zip"
  - wget -nv "https://github.com/Nevcairiel/LAVFilters/releases/download/0.79.2/LAVFilters-0.79.2-%PLATFORM:Win32=x86%.zip"
  - msbuild mpc-hc.sln -t:build -p:Configuration="%CONFIGURATION%" -p:Platform="%PLATFORM%"
  - for /d %%d in (%APPVEYOR_BUILD_FOLDER%\bin\mpc-hc_*) do cd "%%d"
  - tar -xf "%APPVEYOR_BUILD_FOLDER%\exiftool-13.30_%BITNESS%.zip" --strip-components=1
  - ren exiftool(-k).exe exiftool.exe
  - 7z x "%APPVEYOR_BUILD_FOLDER%\LAVFilters-0.79.2-%PLATFORM:Win32=x86%.zip" -oLAVFilters%BITNESS:32=% COPYING *.dll *.ax *.manifest
  - 7z a "%APPVEYOR_BUILD_FOLDER%\bin\%APPVEYOR_REPO_NAME:/=-%_%PLATFORM%_%CONFIGURATION%_v%VERSION%.7z" *.dll *.exe %CONFIGURATION:Debug=*%.pdb LAVFilters%BITNESS:32=% exiftool_files "%APPVEYOR_BUILD_FOLDER%\distrib\%PLATFORM:Win32=x86%\D3D*.dll"

artifacts:
  - path: bin/*.7z
